name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List images
        run: |
          npm run list-images
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: imageList.txt
