name: Build and Deploy to Pages

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List images
        run: |
          npm run list-images
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: imageList.txt
      - name: crop Images to Thumbnail
        run: |
          npm i
          node ./js/cropImages.js 700
      - uses: actions/upload-artifact@master
        with:
          name: image-artifact
          path: ./images/thumbnails/

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download imageList.txt
        uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: ./
      - name: Download thumbnails
        uses: actions/download-artifact@master
        with:
          name: image-artifact
          path: ./images/thumbnails/
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
